name: Generate Markdown

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-markdown:
    name: Generate Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0' # Not needed with a .ruby-version, .tool-versions or mise.toml
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Compile project
        run: cd markdown_printer && mvn -q -e compile
      - name: Generate skills.md
        run: cd markdown_printer && mvn -q -e -DskipTests exec:java -Dexec.mainClass="org.example.Main" > skills.md
      - name: Push skills.md if changed and UI tests pass
        run: |
          bash push_skills_md_if_changed_and_ui_tests_pass.sh