name: UI tests

on:
  deployment_status:
    states: [success]

jobs:
  ui-tests:
    name: UI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: UI tests
        run: make run-ui-tests-ci